TexcelASPNETbyEddy/Controllers/SEController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;


namespace TexcelASPNETbyEddy.Controllers
{
    public class SEController : Controller
    {
        // GET: SE

        //PREMIER COMMIT FRANCK

        //DEUXIEME COMMIT FRANCK

            //premier commit SEControlleur
        BdTexcel_Eddy_FranckEntities bd = new BdTexcel_Eddy_FranckEntities();
        public ActionResult Index()
        {
            return View(bd.tblSEs.ToList());
        }

        [HttpPost]
        public ActionResult Index(string texte)
        {
            List<tblSE> listeResultatRechercheSE = new List<tblSE>();
            var db = new BdTexcel_Eddy_FranckEntities();

            var requeteRechercheSE = from se in db.tblSEs
                                     where se.tagSE.Contains(texte)
                                     select se;

            foreach (var se in requeteRechercheSE)
            {

                tblSE monSE = new tblSE();
                monSE.codeSE = se.codeSE;
                monSE.nomSE = se.nomSE;
                monSE.tagSE = se.tagSE;
                monSE.editionSE = se.editionSE;
                monSE.versionSE = se.versionSE;
                listeResultatRechercheSE.Add(monSE);
            }
            return View(listeResultatRechercheSE.ToList());
        }

        // GET: tblSE/Details/5
        public ActionResult Details(int id = 0)
        {
            return View(bd.tblSEs.Find(id));
        }

        // GET: tblSE/Create
        [HttpGet]
        public ActionResult Create()
        {
            //ViewBag.ErreurCreateSE = false;
            return View();
        }

        // POST: tblSE/Create
        [HttpPost]
        public ActionResult Create(tblSE SE)
        {
            try
            {
                // TODO: Add insert logic here
                if (ModelState.IsValid)
                {
                    if(existenceDuSE(SE) == true)
                    {
                        ViewBag.ErreurSE = true;
                        ViewBag.Message = " Ce système d'exploitation existe déja!!! ";

                        return View(SE);
                    }
                    else
                    {
                        SE.tagSE = SE.nomSE + SE.editionSE + SE.versionSE;
                        bd.tblSEs.Add(SE);
                        bd.SaveChanges();
                        return RedirectToAction("Index");
                    }
                   
                }

                return View(SE);
            }
            catch
            {
                return View(SE);
            }
        }

        // GET: tblSE/Edit/5
        public ActionResult Edit(int id=0)
        {
            return View(bd.tblSEs.Find(id));
        }

        // POST: tblSE/Edit/5
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Edit(tblSE SE)
        {

            try
            {
                SE.tagSE = SE.nomSE + SE.editionSE + SE.versionSE;

                bd.Entry(SE).State = EntityState.Modified;

                bd.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View(SE);
            }
        }

        // GET: tblSE/Delete/5
        public ActionResult Delete(int id)
        {
            return View(bd.tblSEs.Find(id));
        }

        // POST: tblSE/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmation(int id)
        {
            tblSE SE = bd.tblSEs.Find(id);

            try
            {
                // TODO: Add delete logic here
                

                if (nombrePlateformeSE(SE) != 0)
                {
                    ViewBag.ErreurSE = true;
                    ViewBag.Message = " Le système d'exploitation est lié a une ou plusieurs plateformes!!! ";

                    return View(SE);
                }
                else
                {
                    bd.tblSEs.Remove(SE);

                    bd.SaveChanges();

                    return RedirectToAction("Index");
                }

            }
            catch
            {
                return View(SE);
            }

        }

        private bool existenceDuSE(tblSE SE)
        {
            List<tblSE> listeDesSE = bd.tblSEs.ToList();
            bool existeDansLaBD = false;

            foreach (tblSE se in listeDesSE)
            {
                if (se.nomSE == SE.nomSE && se.editionSE == SE.editionSE && se.versionSE == SE.versionSE)
                {
                    existeDansLaBD = true;
                    break;
                }
            }

            return existeDansLaBD;
        }

        private int nombrePlateformeSE(tblSE SE)
        {
            int nbrePlateformeSE = 0;
            var requeteNbrePlateformeSE = from se in bd.tblSEs
                                          where se.codeSE == SE.codeSE
                                          select se.tblPlateformes.Count();

            foreach (var nombre in requeteNbrePlateformeSE)
            {
                nbrePlateformeSE = nombre;
            }

            return nbrePlateformeSE;
        } 

        private List<tblSE> listeDesSE()
        {
           
            List<tblSE> listeDesSE = new List<tblSE>();

            var query = from se in bd.tblSEs
                        orderby se.codeSE
                        select se;

            foreach (var se in query)
            {
                tblSE SE = new tblSE();
                SE.codeSE = se.codeSE;
                SE.nomSE = se.nomSE;
                SE.editionSE = se.editionSE;
                SE.versionSE = se.versionSE;

                listeDesSE.Add(SE);
            }

            return listeDesSE;
        }

    }
}

TexcelASPNETbyEddy/Views/SE/Create.cshtml
@model TexcelASPNETbyEddy.tblSE

@{
    ViewBag.Title = "Ajouter Système d'exploitation";
}

<h2>Ajouter Système d'exploitation</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Système d'exploitation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nomSE," Nom ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nomSE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nomSE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.editionSE, " Edition ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.editionSE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.editionSE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.versionSE, " Version ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.versionSE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.versionSE, "", new { @class = "text-danger" })
            </div>
        </div>

        <!--<div class="form-group">
            Html.LabelFor(model => model.tagSE, htmlAttributes: new { class = "control-label col-md-2" })
            <div class="col-md-10">
                Html.EditorFor(model => model.tagSE, new { htmlAttributes = new { class = "form-control" } })
                Html.ValidationMessageFor(model => model.tagSE, "", new { class = "text-danger" })
            </div>
        </div>-->

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ajouter" class="btn btn-default" />
            </div>
        </div>

        @if (ViewBag.ErreurSE == true)
        {
            <div class="form-group">
                <p style= "color:red;" class="col-md-offset-2 col-md-10"> @ViewBag.Message </p>
            </div>

            ViewBag.ErreurSE = false;
        }
        
    </div>
}



<div>
    @Html.ActionLink("Retourner à la liste", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TexcelASPNETbyEddy/Views/SE/Delete.cshtml
@model TexcelASPNETbyEddy.tblSE

@{
    ViewBag.Title = "Supprimer";
}

<h2>Supprimer</h2>

<h3>Êtes-vous sûr de vouloir supprimer ce système d'exploitation?</h3>
<div>
    <h4>Sytème d'exploitation</h4>
    <hr />

    <dl class="dl-horizontal">
        <dt>
           Nom
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nomSE)
        </dd>

        <dt>
           Edition
        </dt>

        <dd>
            @Html.DisplayFor(model => model.editionSE)
        </dd>

        <dt>
           Version
        </dt>

        <dd>
            @Html.DisplayFor(model => model.versionSE)
        </dd>

        <!--<dt>
            Html.DisplayNameFor(model => model.tagSE)
        </dt>

        <dd>
            Html.DisplayFor(model => model.tagSE)
        </dd>-->

        @if (ViewBag.ErreurSE == true)
        {
            <p style="color:red;">
                @ViewBag.Message 
            </p>

            ViewBag.ErreurSE = false;
        }
        
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Supprimer" class="btn btn-default" /> |
            @Html.ActionLink("Retourner à la lsite", "Index")
        </div>
    }

</div>

TexcelASPNETbyEddy/Views/SE/Details.cshtml
@model TexcelASPNETbyEddy.tblSE

@{
    ViewBag.Title = "Details";
}

<h2>Détails</h2>

<div>
    <h4>Système d'exploitation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <!--@Html.DisplayNameFor(model => model.nomSE)-->
            Nom
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nomSE)
        </dd>

        <dt>
            <!--@Html.DisplayNameFor(model => model.editionSE)-->
            Édition
        </dt>

        <dd>
            @Html.DisplayFor(model => model.editionSE)
        </dd>

        <dt>
            <!--@Html.DisplayNameFor(model => model.versionSE)-->
            Version
        </dt>

        <dd>
            @Html.DisplayFor(model => model.versionSE)
        </dd>

        <!--<dt>
            Html.DisplayNameFor(model => model.tagSE)
        </dt>

        <dd>
            Html.DisplayFor(model => model.tagSE)
        </dd>-->

    </dl>
</div>
<p>
    @Html.ActionLink("Éditer", "Edit", new { id = Model.codeSE }) |
    @Html.ActionLink("Retourner à la liste", "Index")
</p>

TexcelASPNETbyEddy/Views/SE/Edit.cshtml
@model TexcelASPNETbyEddy.tblSE

@{
    ViewBag.Title = "Edit";
}

<h2>Éditer</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Système d'exploitation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.codeSE)

        <div class="form-group">
            @Html.LabelFor(model => model.nomSE, " Nom ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nomSE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nomSE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.editionSE, " Edition ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.editionSE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.editionSE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.versionSE, " Version ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.versionSE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.versionSE, "", new { @class = "text-danger" })
            </div>
        </div>

        @if (ViewBag.ErreurSE == true)
        {
            <div class="form-group">
                <p style="color:red;" class="col-md-offset-2 col-md-10"> @ViewBag.Message </p>
            </div>

            ViewBag.ErreurSE = false;
        }

        <!--<div class="form-group">
            Html.LabelFor(model => model.tagSE, htmlAttributes: new { class = "control-label col-md-2" })
            <div class="col-md-10">
                Html.EditorFor(model => model.tagSE, new { htmlAttributes = new { class = "form-control" } })
                Html.ValidationMessageFor(model => model.tagSE, "", new { class = "text-danger" })
            </div>
        </div>-->

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>

    </div>
}

<div>
    @Html.ActionLink("Retourner à la liste", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TexcelASPNETbyEddy/Views/SE/Index.cshtml
@model IEnumerable<TexcelASPNETbyEddy.tblSE>

@{
    ViewBag.Title = "Index";
}

<h2>Système d'exploitation</h2>


<div class="row">
    <div class="col-md-3">
        @if (Session["Role"].ToString() == "administrateur")
        {
            <p>
                @Html.ActionLink("Créer nouveau", "Create")
            </p>
        }   
    </div>
    <div class="col-md-3">

    </div>

    <div class="col-md-3">
        @using (Html.BeginForm("index", "SE"))
        {
            //Champ texte de recherche
            @Html.TextBox("texte")
            //Input de validation (n'est pas généré par un programme d'assistance)
            <input type="submit" value="Rechercher" />
        }
    </div>
</div>




<table class="table">
    <tr>
        <th>
            <!--@Html.DisplayNameFor(model => model.nomSE)-->
            NOM
        </th>
        <th>
            <!--@Html.DisplayNameFor(model => model.editionSE)-->
            ÉDITION
        </th>
        <th>
            <!--@Html.DisplayNameFor(model => model.versionSE)-->
            VERSION
        </th>
        <!--<th>
             Html.DisplayNameFor(model => model.tagSE)
            TAG
        </th>-->
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nomSE)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.editionSE)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.versionSE)
        </td>
        <!--
        <td>
            @Html.DisplayFor(modelItem => item.tagSE)
        </td>-->

        <!--<td>
            Html.DisplayFor(modelItem => item.tagSE)
        </td>-->
        <td>
            @Html.ActionLink("Editer", "Edit", new { id=item.codeSE }) |
            @Html.ActionLink("Details", "Details", new { id=item.codeSE }) |
            @Html.ActionLink("Effacer", "Delete", new { id=item.codeSE })
        </td>
    </tr>
}

</table>