TexcelASPNETbyEddy/Models/JeuViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TexcelASPNETbyEddy.Models
{
    public class JeuViewModel
    {
        public int idJeu { get; set; }
        public string nomJeu { get; set; }
        public string descriptionJeu { get; set; }
        public string devellopeurJeu { get; set; }
        public string configurationMinimaleJeu { get; set; }
        public List<CheckBoxViewModel> lesGenres { get; set; }
        public List<CheckBoxViewModel> lesClassifications { get; set; }
        public List<CheckBoxViewModel> lesThemes { get; set; }
    }
}

TexcelASPNETbyEddy/Controllers/JeuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Windows;
using TexcelASPNETbyEddy.Models;

namespace TexcelASPNETbyEddy.Controllers
{
    public class JeuController : Controller
    {
        // GET: Jeu

        BdTexcel_Eddy_FranckEntities bd = new BdTexcel_Eddy_FranckEntities();
        public ActionResult Index()
        {
            return View(bd.tblJeus.ToList());
        }

        [HttpPost]
        public ActionResult Index(string texte)
        {

            List<tblJeu> listeResultatRechercheJeu = new List<tblJeu>();
            var db = new BdTexcel_Eddy_FranckEntities();

            var requeteRechercheJeu = from jeu in db.tblJeus
                                             where (jeu.tag.Contains(texte)) //|| (jeu.tblTypePlateforme.nomTypePlateforme.Contains(texte)) || (plateforme.tblSE.nomSE.Contains(texte))
                                             select jeu;

            foreach (var jeu in requeteRechercheJeu)
            {

                tblJeu monJeu = new tblJeu();
                monJeu.idJeu = jeu.idJeu;
                monJeu.idProjetTest = jeu.idProjetTest;
                monJeu.nomJeu = jeu.nomJeu;
                monJeu.tag = jeu.tag;
                monJeu.tblClassifications = jeu.tblClassifications;
                monJeu.tblGenres = jeu.tblGenres;
                monJeu.tblPlateformes = jeu.tblPlateformes;
                monJeu.tblProjetTest = jeu.tblProjetTest;
                monJeu.tblThemes = jeu.tblThemes;
                monJeu.devellopeurJeu = jeu.devellopeurJeu;
                monJeu.descriptionJeu = jeu.descriptionJeu;
                monJeu.configurationMinimaleJeu = jeu.configurationMinimaleJeu; 
                listeResultatRechercheJeu.Add(monJeu);



                /*
                maPlateforme.idPlateforme = plateforme.idPlateforme;
                maPlateforme.idTypePlateforme = plateforme.idTypePlateforme;
                //maPlateforme.tblTypePlateforme.nomTypePlateforme;
                maPlateforme.configurationPlateforme = plateforme.configurationPlateforme;
                maPlateforme.codeSE = plateforme.codeSE;
                maPlateforme.nomPlateforme = plateforme.nomPlateforme;
                maPlateforme.tagPlateforme = plateforme.tagPlateforme;
                //maPlateforme.tblJeus = plateforme.tblJeus;
                maPlateforme.tblSE = plateforme.tblSE;
                maPlateforme.tblTypePlateforme = plateforme.tblTypePlateforme;
                listeResultatRecherchePlateforme.Add(maPlateforme);
                */
            }
            return View(listeResultatRechercheJeu.ToList());
            // return View(bd.tblPlateformes.ToList());
        }


        public ActionResult Details(int id = 0)
        {
            return View(bd.tblJeus.Find(id));
        }

        public ActionResult Edit(int id = 0)
        {
            tblJeu jeu = bd.tblJeus.Find(id);

            /*var result = from genre in bd.tblGenres
                         select new
                         {
                             genre.idGenre,
                             genre.descriptionGenre,
                             Checked = ((from jg in bd.JeuGenre where (jg.idJeu == jeu.idJeu)&(jg.idGenre == genre.idGenre) select jg).Count()>0)
                         };*/

            var checkBoxListGenre = new List<CheckBoxViewModel>();
            var checkBoxListTheme = new List<CheckBoxViewModel>();
            var checkBoxListClassification = new List<CheckBoxViewModel>();

            foreach (tblGenre genre in bd.tblGenres)
            {
                CheckBoxViewModel newCheckBoxViewModel = new CheckBoxViewModel();

                newCheckBoxViewModel.Id = genre.idGenre;
                newCheckBoxViewModel.Description = genre.descriptionGenre;
                newCheckBoxViewModel.Checked = jeuDansUneListe(genre.tblJeus, jeu);
                checkBoxListGenre.Add(newCheckBoxViewModel);
            }

            foreach (tblTheme theme in bd.tblThemes)
            {
                CheckBoxViewModel newCheckBoxViewModel = new CheckBoxViewModel();

                newCheckBoxViewModel.Id = theme.idTheme;
                newCheckBoxViewModel.Description = theme.descriptionTheme;
                newCheckBoxViewModel.Checked = jeuDansUneListe(theme.tblJeus, jeu);
                checkBoxListTheme.Add(newCheckBoxViewModel);
            }

            foreach (tblClassification classification in bd.tblClassifications)
            {
                CheckBoxViewModel newCheckBoxViewModel = new CheckBoxViewModel();

                newCheckBoxViewModel.Id = classification.idClassification;
                newCheckBoxViewModel.Description = classification.descriptionClassification;
                newCheckBoxViewModel.Checked = jeuDansUneListe(classification.tblJeus, jeu);
                checkBoxListClassification.Add(newCheckBoxViewModel);
            }

            var myJeuViewModel = new JeuViewModel();

            myJeuViewModel.configurationMinimaleJeu = jeu.configurationMinimaleJeu;

            myJeuViewModel.devellopeurJeu = jeu.devellopeurJeu;

            myJeuViewModel.descriptionJeu = jeu.descriptionJeu;

            myJeuViewModel.nomJeu = jeu.nomJeu;

            /*foreach (var genre in result)
            {
                myCheckBoxList.Add(new CheckBoxViewModel { Id = genre.idGenre, Description = genre.descriptionGenre, Checked = genre.Checked });
            }*/

            myJeuViewModel.lesGenres = checkBoxListGenre;

            myJeuViewModel.lesThemes = checkBoxListTheme;

            myJeuViewModel.lesClassifications = checkBoxListClassification;

            return View(myJeuViewModel);
        }


        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Edit(JeuViewModel j)
        {
            
                /*tblJeu jeu = bd.tblJeus.Find(j.idJeu);
                jeu.devellopeurJeu = j.devellopeurJeu;
                jeu.descriptionJeu = j.descriptionJeu;
                jeu.configurationMinimaleJeu = j.configurationMinimaleJeu;
                jeu.nomJ0eu = j.nomJeu;

                foreach (tblClassification cl in bd.tblClassifications)
                {
                    foreach (tblClassification CL in jeu.tblClassifications)
                    {
                        if(CL.idClassification == cl.idClassification)
                        {
                            bd.tblClassifications.Find(cl.idClassification).tblJeus.Remove(jeu);
                        }
                    }
                }

                foreach (tblTheme th in bd.tblThemes)
                {
                    foreach (tblTheme TH in jeu.tblThemes)
                    {
                        if (TH.idTheme == th.idTheme)
                        {
                            bd.tblThemes.Find(th.idTheme).tblJeus.Remove(jeu);
                        }
                    }
                }

                foreach (tblGenre ge in bd.tblGenres)
                {
                    foreach (tblGenre GE in jeu.tblGenres)
                    {
                        if (GE.idGenre == ge.idGenre)
                        {
                            bd.tblGenres.Find(ge.idGenre).tblJeus.Remove(jeu);
                        }
                    }
                }

                foreach (tblJeu J in bd.tblJeus)
                {
                    if (J.idJeu == j.idJeu)
                    {
                        J.tblGenres.Clear();
                        J.tblClassifications.Clear();
                        J.tblThemes.Clear();
                    }
                }

                foreach (var genre in j.lesGenres)
                {
                    if(genre.Checked)
                    {

                        tblGenre newGenre = new tblGenre();
                        newGenre.descriptionGenre = genre.Description;
                        newGenre.idGenre = genre.Id;

                        bd.tblGenres.Find(genre.Id).tblJeus.Add(jeu);
                        bd.tblJeus.Find(jeu.idJeu).tblGenres.Add(newGenre);
                    }
                }

                foreach (var cl in j.lesClassifications)
                {
                    if (cl.Checked)
                    {

                        tblClassification newCL = new tblClassification();
                        newCL.descriptionClassification = cl.Description;
                        newCL.idClassification = cl.Id;

                        bd.tblClassifications.Find(cl.Id).tblJeus.Add(jeu);
                        bd.tblJeus.Find(jeu.idJeu).tblClassifications.Add(newCL);
                    }
                }

                foreach (var th in j.lesThemes)
                {
                    if (th.Checked)
                    {
                        tblTheme newTH = new tblTheme();
                        newTH.descriptionTheme = th.Description;
                        newTH.idTheme = th.Id;

                        bd.tblThemes.Find(th.Id).tblJeus.Add(jeu);
                        bd.tblJeus.Find(jeu.idJeu).tblThemes.Add(newTH);
                    }
                }
                /*foreach (tblClassification cl in bd.tblClassifications)
                {
                    foreach (tblClassification CL in jeu.tblClassifications)
                    {
                        if (CL.idClassification == cl.idClassification)
                        {
                            bd.tblClassifications.Find(cl.idClassification).tblJeus.Remove(jeu);
                        }
                    }
                }*/

                //bd.Entry(jeu).State = System.Data.Entity.EntityState.Modified;*/
                try
                {
                    tblJeu jeu = bd.tblJeus.Find(j.idJeu);

                    jeu.devellopeurJeu = j.devellopeurJeu;
                    jeu.descriptionJeu = j.descriptionJeu;

TexcelASPNETbyEddy/Views/Jeu/Create.cshtml
@model TexcelASPNETbyEddy.tblJeu

@{
    ViewBag.Title = "Créer jeu";
}

<h2>Créer jeu</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Jeu</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nomJeu," Nom ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nomJeu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nomJeu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.devellopeurJeu,"  Devellopeur ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.devellopeurJeu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.devellopeurJeu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descriptionJeu, "  Description ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descriptionJeu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descriptionJeu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.configurationMinimaleJeu, "  Configuration minimale ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.configurationMinimaleJeu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.configurationMinimaleJeu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Créer" class="btn btn-default" />
            </div>
        </div>

    </div>
}

<div>
    @Html.ActionLink("Retourner à la liste", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TexcelASPNETbyEddy/Views/Jeu/Details.cshtml
@model TexcelASPNETbyEddy.tblJeu

@{
    ViewBag.Title = "Détails";
}

<h2>Détails</h2>

<div>
    <h4>Jeu</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            NOM
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nomJeu)
        </dd>

        <dt>
            DEVELLOPEUR
        </dt>

        <dd>
            @Html.DisplayFor(model => model.devellopeurJeu)
        </dd>

        <dt>
            DESCRIPTION
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descriptionJeu)
        </dd>

        <dt>
           CONFIGURATION
        </dt>

        <dd>
            @Html.DisplayFor(model => model.configurationMinimaleJeu)
        </dd>

        <dt>
           GENRE(S)
        </dt>

        <dd>
            @{

                string lesGenres = "";

                foreach (var genres in Model.tblGenres)
                {

                    lesGenres = genres.descriptionGenre + ", "+ lesGenres;


                }

                <p> @lesGenres</p>

            }   
        </dd>

        <dt>
            CLASSIFICATION(S)
        </dt>

        <dd>
            @{   

                string lesClassifications = "";

                foreach (var classification in Model.tblClassifications)
                {
                    lesClassifications = classification.descriptionClassification + ", " + lesClassifications;
                }

                <p>@lesClassifications</p>
            }
        </dd>

        <dt>
            THEME(S)
        </dt>

        <dd>
            @{

                string lesThemes = "";

                foreach (var theme in Model.tblThemes)
                {
                    lesThemes = theme.descriptionTheme + ", "+lesThemes;
                }

                <p>@lesThemes</p>
            }
        </dd>



    </dl>
</div>
<p>
    @Html.ActionLink("Éditer", "Edit", new { id = Model.idJeu }) |
    @Html.ActionLink("Retour à la liste", "Index")
</p>

TexcelASPNETbyEddy/Views/Jeu/Edit.cshtml
@model TexcelASPNETbyEddy.Models.JeuViewModel

@{
    ViewBag.Title = "Éditer";
}

<h2>Éditer</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Jeu</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idJeu)

        <div class="form-group">
            @Html.LabelFor(Model => Model.nomJeu," Nom ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(Model => Model.nomJeu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(Model => Model.nomJeu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(Model => Model.devellopeurJeu, " Devellopeur ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(Model => Model.devellopeurJeu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(Model => Model.devellopeurJeu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(Model => Model.descriptionJeu, " Description ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(Model => Model.descriptionJeu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(Model => Model.descriptionJeu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(Model => Model.configurationMinimaleJeu, " Configuration ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(Model => Model.configurationMinimaleJeu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.configurationMinimaleJeu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(Model => Model.lesGenres, " Genres ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @for(int i=0; i < Model.lesGenres.Count();i++)
                {
                    @Html.EditorFor(m=> Model.lesGenres[i].Checked)
                    @Html.DisplayFor(m=> Model.lesGenres[i].Description)

                    @Html.HiddenFor(m=> Model.lesGenres[i].Description)
                    @Html.HiddenFor(m => Model.lesGenres[i].Id)

                    //<span style="visibility:hidden;">ppp</span>//espace
                }
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(Model => Model.lesThemes, " Themes ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @for (int i = 0; i < Model.lesThemes.Count(); i++)
                {
                    @Html.EditorFor(m => Model.lesThemes[i].Checked)
                    @Html.DisplayFor(m => Model.lesThemes[i].Description)

                    @Html.HiddenFor(m => Model.lesThemes[i].Description)
                    @Html.HiddenFor(m => Model.lesThemes[i].Id)

                    //<span style="visibility:hidden;">ppp</span>//espace
                }
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(Model => Model.lesClassifications, " Classifications ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @for (int i = 0; i < Model.lesClassifications.Count(); i++)
                {
                    @Html.EditorFor(m => Model.lesClassifications[i].Checked)
                    @Html.DisplayFor(m => Model.lesClassifications[i].Description)

                    @Html.HiddenFor(m => Model.lesClassifications[i].Description)
                    @Html.HiddenFor(m => Model.lesClassifications[i].Id)

                    <span style="visibility:hidden;">ppp</span>//espace
                }
            </div>
        </div>

        <!--<div class="form-group">
            Html.LabelFor(model => model.idProjetTest, "idProjetTest", htmlAttributes: new { class = "control-label col-md-2" })
            <div class="col-md-10">
                Html.DropDownList("idProjetTest", null, htmlAttributes: new{ class = "form-control" })
                Html.ValidationMessageFor(model => model.idProjetTest, "", new { class = "text-danger" })
            </div>
        </div>-->

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Enregistrer" class="btn btn-default" />
            </div>
        </div>

    </div>
}

<div>
    @Html.ActionLink("Retour à la liste", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TexcelASPNETbyEddy/Views/Jeu/Index.cshtml
@model IEnumerable<TexcelASPNETbyEddy.tblJeu>

@{
    ViewBag.Title = "Jeux";
}

<h2>Jeux</h2>

<div class="row">

    <div class="col-md-3">
        @if (Session["Role"].ToString() == "administrateur")
        {
            <p>
                @Html.ActionLink("Créer nouveau", "Create")
            </p>
        }
    </div>

    <div class="col-md-3">

    </div>

    <div class="col-md-3">
        @using (Html.BeginForm("Index", "Jeu"))
        {
            //Champ texte de recherche
            @Html.TextBox("texte")
            //Input de validation (n'est pas généré par un programme d'assistance)
            <input type="submit" value="Rechercher" />
        }
    </div>
</div>
<table class="table">
    <tr>
        <th>
            NOM
        </th>
        <th>
           DEVELLOPEUR
        </th>
        <th>
           DESCRIPTION 
        </th>
        <th>
           CONFIGURATION MINIMALE
        </th>

        <th>
           GENRE
        </th>
        <!--<th>
           Html.DisplayNameFor(model => model.tag)
        </th>-->
        <!--<th>
            Html.DisplayNameFor(model => model.tblProjetTest.nomProjetTest)
        </th>-->
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nomJeu)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.devellopeurJeu)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.descriptionJeu)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.configurationMinimaleJeu)
        </td>

        <td>
            @foreach (var genres in item.tblGenres)
            {
                <p> @Html.DisplayFor(modelItem => genres.descriptionGenre)</p>
            }
        </td>
        
       
        <!--<td>
            Html.DisplayFor(modelItem => item.tag)
        </td>-->
        <!--<td>
            Html.DisplayFor(modelItem => item.tblProjetTest.nomProjetTest)
        </td>-->
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.idJeu }) |
            @Html.ActionLink("Details", "Details", new { id=item.idJeu }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.idJeu })
        </td>
    </tr>
}

</table>