TexcelASPNETbyEddy/Controllers/PlateformeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace TexcelASPNETbyEddy.Controllers
{
    public class PlateformeController : Controller
    {
        // GET: Plateforme
        BdTexcel_Eddy_FranckEntities bd = new BdTexcel_Eddy_FranckEntities();

        public ActionResult Index()
        {
            return View(bd.tblPlateformes.ToList());
        }
        [HttpPost]
        public ActionResult Index(string texte)
        {

            List<tblPlateforme> listeResultatRecherchePlateforme = new List<tblPlateforme>();
            var db = new BdTexcel_Eddy_FranckEntities();

            var requeteRecherchePlateforme = from plateforme in db.tblPlateformes
                                     where (plateforme.tagPlateforme.Contains(texte))||(plateforme.tblTypePlateforme.nomTypePlateforme.Contains(texte)) || (plateforme.tblSE.nomSE.Contains(texte))
                                             select plateforme;

            foreach (var plateforme in requeteRecherchePlateforme)
            {

                tblPlateforme maPlateforme = new tblPlateforme();
                maPlateforme.idPlateforme = plateforme.idPlateforme;
                maPlateforme.idTypePlateforme = plateforme.idTypePlateforme;
                //maPlateforme.tblTypePlateforme.nomTypePlateforme;
                maPlateforme.configurationPlateforme = plateforme.configurationPlateforme;
                maPlateforme.codeSE = plateforme.codeSE;
                maPlateforme.nomPlateforme = plateforme.nomPlateforme;
                maPlateforme.tagPlateforme = plateforme.tagPlateforme;
                //maPlateforme.tblJeus = plateforme.tblJeus;
                maPlateforme.tblSE = plateforme.tblSE;
                maPlateforme.tblTypePlateforme = plateforme.tblTypePlateforme;
                listeResultatRecherchePlateforme.Add(maPlateforme);
            }
            return View(listeResultatRecherchePlateforme.ToList());
            // return View(bd.tblPlateformes.ToList());
        }



        public ActionResult Details(int id = 0)
        {
            return View(bd.tblPlateformes.Find(id));
        }
        public ActionResult Create()
        {
            //ViewBag.ErreurCreateSE = false;
            ViewBag.TypePlateformes = new SelectList(bd.tblTypePlateformes, "idTypePlateforme","nomTypePlateforme");

            ViewBag.SE = new SelectList(bd.tblSEs, "codeSE", "nomSE");

            //ViewData["TypePlateformes"] = new SelectList(bd.tblTypePlateformes, "idTypePlateforme", "nomTypePlateforme");

            //ViewData["SE"] = new SelectList(bd.tblSEs, "codeSE", "nomSE");

            return View();
        }

        [HttpPost]
        public ActionResult Create(tblPlateforme plateforme)
        {
            try
            {

                ViewBag.TypePlateformes = new SelectList(bd.tblTypePlateformes, "idTypePlateforme", "nomTypePlateforme");

                ViewBag.SE = new SelectList(bd.tblSEs, "codeSE", "nomSE");

                // TODO: Add insert logic here
                if (ModelState.IsValid)
                {
                    if (existenceDeLaPlateforme(plateforme) == true)
                    {
                        ViewBag.ErreurPlateforme = true;
                        ViewBag.Message = " Cette plateforme existe déja!!! ";

                        return View(plateforme);
                    }
                    else
                    {
                        // plateforme.tagPlateforme = plateforme.nomPlateforme + plateforme.configurationPlateforme + plateforme.tblTypePlateforme.nomTypePlateforme + plateforme.tblSE.nomSE;
                        plateforme.tagPlateforme = plateforme.nomPlateforme + plateforme.configurationPlateforme;
                        bd.tblPlateformes.Add(plateforme);
                        bd.SaveChanges();
                        return RedirectToAction("Index");
                    }

                }

                return View(plateforme);
            }
            catch
            {
                return View(plateforme);
            }
        }

        public ActionResult Edit(int id = 0)
        {
            //ViewData["TypePlateformes"] = new SelectList(bd.tblTypePlateformes, "idTypePlateforme", "nomTypePlateforme");

            //ViewData["SE"] = new SelectList(bd.tblSEs, "codeSE", "nomSE");

            ViewBag.TypePlateformes = new SelectList(bd.tblTypePlateformes, "idTypePlateforme", "nomTypePlateforme");

            ViewBag.SE = new SelectList(bd.tblSEs, "codeSE", "nomSE");

            return View(bd.tblPlateformes.Find(id));
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Edit(tblPlateforme Plateforme)
        {

            try
            {
                Plateforme.tagPlateforme = Plateforme.nomPlateforme + Plateforme.configurationPlateforme;

                bd.Entry(Plateforme).State = EntityState.Modified;

                bd.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View(Plateforme);
            }
        }

        public ActionResult Delete(int id)
        {
            return View(bd.tblPlateformes.Find(id));
        }


        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmation(int id)
        {
            tblPlateforme plateforme = bd.tblPlateformes.Find(id);

            try
            {
                // TODO: Add delete logic here
                if (nombreJeuPlateforme(plateforme) != 0)
                {
                    ViewBag.ErreurPlateforme = true;
                    ViewBag.Message = " Impossible!!! La plateforme est liée à un ou plusieurs jeux. ";

                    return View(plateforme);
                }
                else
                {
                    bd.tblPlateformes.Remove(plateforme);

                    bd.SaveChanges();

                    return RedirectToAction("Index");
                }

            }
            catch
            {
                return View(plateforme);
            }

        }

        private bool existenceDeLaPlateforme(tblPlateforme plateforme)
        {
            List<tblPlateforme> listeDesPlateforme = bd.tblPlateformes.ToList();
            bool existeDansLaBD = false;

            foreach (tblPlateforme pl in listeDesPlateforme)
            {
                if (pl.nomPlateforme == plateforme.nomPlateforme && pl.configurationPlateforme == plateforme.configurationPlateforme && pl.idTypePlateforme == plateforme.idTypePlateforme&& pl.codeSE == plateforme.codeSE)
                {
                    existeDansLaBD = true;
                    break;
                }
            }

            return existeDansLaBD;
        }

        private int nombreJeuPlateforme(tblPlateforme Plateforme)
        {
            int nbreJeuDeLaPlateforme = 0;
            var requeteNbreJeuDeLaPlateforme = from plateforme in bd.tblPlateformes
                                               where plateforme.idPlateforme == Plateforme.idPlateforme
                                               select plateforme.tblJeus.Count();

            foreach (var nombre in requeteNbreJeuDeLaPlateforme)
            {
                nbreJeuDeLaPlateforme = nombre;
            }

            return nbreJeuDeLaPlateforme;

        }

        private List<tblPlateforme> listeDesPlateformes()
        {

            List<tblPlateforme> listeDesPlateformes = new List<tblPlateforme>();

            var query = from plateforme in bd.tblPlateformes
                        orderby plateforme.idPlateforme
                        select plateforme;

            foreach (var plateforme in query)
            {
                tblPlateforme newPlateforme = new tblPlateforme();
                newPlateforme.idPlateforme = plateforme.idPlateforme;
                newPlateforme.nomPlateforme = plateforme.nomPlateforme;
                newPlateforme.configurationPlateforme = plateforme.configurationPlateforme;
                newPlateforme.idTypePlateforme = plateforme.idTypePlateforme;
                newPlateforme.codeSE = plateforme.codeSE;
               
                listeDesPlateformes.Add(newPlateforme);
            }

            return listeDesPlateformes;
        }

    }
}

TexcelASPNETbyEddy/Views/Plateforme/Create.cshtml
@model TexcelASPNETbyEddy.tblPlateforme

@{
    ViewBag.Title = "Ajouter une plateforme";
}

<h2>Ajouter une plateforme</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Plateforme</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nomPlateforme, " Nom  ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nomPlateforme, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nomPlateforme, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.configurationPlateforme," Configuration  ",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.configurationPlateforme, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.configurationPlateforme, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idTypePlateforme, "Type de la plateforme", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.idTypePlateforme, ViewBag.TypePlateformes as SelectList , htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.tblTypePlateforme.nomTypePlateforme, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.codeSE, "Système d'exploitation", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.codeSE, ViewBag.SE as SelectList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.codeSE, "", new { @class = "text-danger" })
            </div>
        </div>

        @if (ViewBag.ErreurPlateforme == true)
        {
            <div class="form-group">
                <p style="color:red;" class="col-md-offset-2 col-md-10"> @ViewBag.Message </p>
            </div>

            ViewBag.ErreurPlateforme = false;
        }
 
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ajouter" class="btn btn-default" />
            </div>
        </div>

    </div>
}

<div>
    @Html.ActionLink("Retour à la liste", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TexcelASPNETbyEddy/Views/Plateforme/Delete.cshtml
@model TexcelASPNETbyEddy.tblPlateforme

@{
    ViewBag.Title = "Supprimer";
}

<h2>Supprimer</h2>

<h3>Êtes-vous sûr de vouloir supprimer cette plateforme?</h3>
<div>
    <h4>Plateforme</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <!--@Html.DisplayNameFor(model => model.nomPlateforme)-->
            Nom
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nomPlateforme)
        </dd>

        <dt>
           <!-- @Html.DisplayNameFor(model => model.configurationPlateforme)-->
            Configuration
        </dt>

        <dd>
            @Html.DisplayFor(model => model.configurationPlateforme)
        </dd>

        <!--<dt>
            Html.DisplayNameFor(model => model.tagPlateforme)
        </dt>

        <dd>
            Html.DisplayFor(model => model.tagPlateforme)
        </dd>-->

        <dt>
            <!--@Html.DisplayNameFor(model => model.tblSE.nomSE)-->
            Système d'exploitation
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblSE.nomSE)
        </dd>

        <dt>
            <!--@Html.DisplayNameFor(model => model.tblTypePlateforme.nomTypePlateforme)-->
            Type de plateforme
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblTypePlateforme.nomTypePlateforme)
        </dd>

        @if (ViewBag.ErreurPlateforme == true)
        {
            <p style="color:red;">
                @ViewBag.Message
            </p>

            ViewBag.ErreurPlateforme = false;
        }

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Supprimer" class="btn btn-default" /> |
            @Html.ActionLink("Retour à la liste", "Index")
        </div>
    }
</div>

TexcelASPNETbyEddy/Views/Plateforme/Details.cshtml
@model TexcelASPNETbyEddy.tblPlateforme

@{
    ViewBag.Title = "Détails";
}

<h2>Détails</h2>

<div>
    <h4>Plateforme</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <!--@Html.DisplayNameFor(model => model.nomPlateforme)-->
            Nom
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nomPlateforme)
        </dd>

        <dt>
           <!-- @Html.DisplayNameFor(model => model.configurationPlateforme)-->
            Configuration
        </dt>

        <dd>
            @Html.DisplayFor(model => model.configurationPlateforme)
        </dd>

        <!--<dt>
            Html.DisplayNameFor(model => model.tagPlateforme)
        </dt>

        <dd>
            Html.DisplayFor(model => model.tagPlateforme)
        </dd>-->

        <dt>
            <!--@Html.DisplayNameFor(model => model.tblSE.nomSE)-->
            Système d'exploitation
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblSE.nomSE)
        </dd>

        <dt>
            <!--@Html.DisplayNameFor(model => model.tblTypePlateforme.nomTypePlateforme)-->
            Type de plpateforme
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblTypePlateforme.nomTypePlateforme)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Éditer", "Edit", new { id = Model.idPlateforme }) |
    @Html.ActionLink("Retourner à la liste", "Index")
</p>

TexcelASPNETbyEddy/Views/Plateforme/Edit.cshtml
@model TexcelASPNETbyEddy.tblPlateforme

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Plateforme</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idPlateforme)

        <div class="form-group">
            @Html.LabelFor(model => model.nomPlateforme, " Nom ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nomPlateforme, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nomPlateforme, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.configurationPlateforme," Configuration ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.configurationPlateforme, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.configurationPlateforme, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idTypePlateforme, "Type de la plateforme", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idTypePlateforme", (SelectList)ViewBag.TypePlateformes, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idTypePlateforme, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.codeSE, "Système d'exploitation", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("codeSE", (SelectList)ViewBag.SE, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.codeSE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>

    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TexcelASPNETbyEddy/Views/Plateforme/Index.cshtml
@model IEnumerable<TexcelASPNETbyEddy.tblPlateforme>

@{
    ViewBag.Title = "Plateformes";
}


<h2>Plateformes</h2>

<div class="row">

    <div class="col-md-3">
        @if (Session["Role"].ToString() == "administrateur")
        {
            <p>
                @Html.ActionLink("Créer nouvelle", "Create")
            </p>
        }   
    </div>
   
    <div class="col-md-3">

    </div>

    <div class="col-md-3">
        @using (Html.BeginForm("index", "Plateforme"))
        {
            //Champ texte de recherche
            @Html.TextBox("texte")
            //Input de validation (n'est pas généré par un programme d'assistance)
            <input type="submit" value="Rechercher" />
        }
    </div>
</div>

<table class="table">
    <tr>
        <th>
           NOM
        </th>
        <th>
           CONFIGURATION
        </th>
        <th>
           SYSTÈME D'EXPLOITATION
        </th>
        <th>
           TYPE DE PLATEFORME
        </th>
        <!--<th>
            TAG
        </th>-->
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nomPlateforme)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.configurationPlateforme)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tblSE.nomSE)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tblTypePlateforme.nomTypePlateforme)
        </td>
        <!--
        <td>
            @*Html.DisplayFor(modelItem => item.tagPlateforme)*@
        </td>-->

        <td>
            @Html.ActionLink("Editer", "Edit", new { id=item.idPlateforme }) |
            @Html.ActionLink("Details", "Details", new { id=item.idPlateforme }) |
            @Html.ActionLink("Effacer", "Delete", new { id=item.idPlateforme })
        </td>
    </tr>
}

</table>