TexcelASPNETbyEddy/Controllers/GerantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TexcelASPNETbyEddy.Controllers
{
    public class GerantController : Controller
    {
        // GET: Gerant
        BdTexcel_Eddy_FranckEntities bd = new BdTexcel_Eddy_FranckEntities();
        public ActionResult Index()
        {
            Session["NomPrenom"] = null;
            Session["UserID"] = null;
            Session["UserName"] = null;
            Session["UserPassword"] = null;
            Session["Role"] = null;

            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Index(tblGerant gerant)
        {
            try
            {
                var usr = bd.tblGerants.Single(u => u.loginGerant == gerant.loginGerant && u.motDePasseGerant == gerant.motDePasseGerant);

                var query = from employe in bd.tblEmployes
                            where employe.idEmploye == usr.idGerant
                            select employe;

                foreach(var employe in query)
                {
                    Session["NomPrenom"] = employe.prenomEmploye +" "+ employe.nomEmploye;
                }

                Session["UserID"] = usr.idGerant.ToString();
                Session["UserName"] = usr.loginGerant.ToString();
                Session["UserPassword"] = usr.motDePasseGerant.ToString();
                Session["Role"] = usr.roleGerant.ToString();

                return RedirectToAction("Index","Home");
            }
            catch
            {
                ModelState.AddModelError(" ", " User or password are wrong!!!! ");

                ViewBag.ErrorLogin = true;

                return View();
            }
        }

    }
}

TexcelASPNETbyEddy/Views/Gerant/Index.cshtml
@model TexcelASPNETbyEddy.tblGerant

@{
    ViewBag.Title = "Index";
}

<h2>Bienvenue sur Texcel</h2>

<div class="row">
    <div class="col-md-12">
        <section>
            @using (Html.BeginForm("Index", "Gerant"))
            {
                @Html.AntiForgeryToken()
                <h4>Connectez-vous</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(m => m.loginGerant,"Nom utilisateur", new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.loginGerant, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.loginGerant, "", new { @class = "text-danger" })
                    </div>
                </div>

                <br/>

                <div class="form-group" style="margin-top:2%;">
                    @Html.LabelFor(m => m.motDePasseGerant, "Mot de passe", new { @class = "col-md-2 control-label" })
                    <div class="col-md-6">
                        @Html.TextBoxFor(m => m.motDePasseGerant, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.motDePasseGerant, "", new { @class = "text-danger" })
                    </div>
                </div>

                <br />

                <div class="form-group" style="margin-top:2%;">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Connexion" class="btn btn-default" />
                    </div>
                </div>

                if (ViewBag.ErrorLogin == true)
                {
                    <p class="col-md-offset-2 col-md-10" style="color:red;">User or password are wrong!!!!</p>
                }

            }
        </section>
    </div>

</div>